### ISSUE TITLE
Use of NTLM authentication rather than STS

### ISSUE THREAD

**Issue by ropdor** [Plaristote/sharepoint-ruby#10]
Hi,

it's not obvious how one would use NTLM authentication rather than an STS, though code in sharepoint-http-auth indicates this is possible. Could you point me to documentation or an example on how this could be done?

**Comment by Plaristote** [comment]
You're right indeed, there was no documentation about this authentication method ! I've modified the README: https://github.com/Plaristote/sharepoint-ruby/commit/0c2066fdbf2229a19ef77ea9e84cb220b6ad2a74

**Comment by ropdor** [comment]
Great, thanks
