### ISSUE TITLE
Ability to authenticate with OAuth

### ISSUE THREAD

**Issue by eamers** [Plaristote/sharepoint-ruby#11]
Is it possible to circumvent the username / password authentication and use an OAuth access token?  I'd be happy to assist, I'm just not sure how to retrieve the required FedAuth and rtFa values once authenticated.

**Comment by Plaristote** [comment]
It seems like you don't need the FedAuth and rtFa variables when using OAuth (see https://msdn.microsoft.com/en-us/magazine/dn198245.aspx). You need to use the Authorization header.

`Sharepoint::Site` has an attribute called `session`, which you can easily overload to implement what you need. Session objects can implement a method called `curl`, to interact with the curl object before a request is sent. So the proper procedure is simply to implement your own session class and set it onto your `Sharepoint::Site` instance.

Here's an example (I haven't tested it, I don't have a working environment right now, but that's the spirit):
```Ruby
class OAuthSession
  attr_accessor :cookie, :token

  def curl curl
    curl.headers["Authorization"] = "Bearer #{@token}"
  end
end

site = Sharepoint::Site.new 'mysite.sharepoint.com', 'server-relative-site-url'
site.session = OAuthSession.new
site.session.token = "your_oauth_token"
# You're good to go
```
