### ISSUE TITLE
STS Endpoint example is wrong

### ISSUE THREAD

**Issue by twohlix** [Plaristote/sharepoint-ruby#15]
The Readme explains that Site.new accepts: `site = Sharepoint::Site.new 'mysite.sharepoint.com', 'site-name', 'https://sts_url.com/extSTS.srf'`

but this is wrong as a 3rd argument errors with exception. According to the source, setting the sts endpoint happens in the `Session.authenticate` method: https://github.com/Plaristote/sharepoint-ruby/blob/master/lib/sharepoint-session.rb#L44

I would do a pull request to fix the readme but am currently a bit too busy. Leaving this as a placeholder.

**Comment by Plaristote** [comment]
I fixed the issue on the README, Thanks for the heads up.
