### ISSUE TITLE
Adding item to a list

### ISSUE THREAD

**Issue by lucasrossi90** [Plaristote/sharepoint-ruby#19]
Hi, Plaristote. I want to thank you for the gem and for sharing your work. 

I'm a bit new at this, so i'd like to know if it's possible to add an item to a Sharepoint List. The README talks about adding an object to a collection, ¿is that related? ¿How do i set the parent of the GenericSharepointObject to add to the list?

Sorry for my english, my "natural" language is spanish (castellano).
Thanks again.

**Comment by Plaristote** [comment]
To add an item to the list, you must set the `parent` attribute on an item.
```
list_item.parent = site.list 'Documents'
list_item.save
```
