### ISSUE TITLE
0.1.3 provides no way to access legacy 'internal' locations

### ISSUE THREAD

**Issue by CJKinni** [Plaristote/sharepoint-ruby#45]
I have automations that use company.sharepoint.com/internal/folder as a valid location.  Previously, I was able to access these locations as well as 'sites/site-name' locations.  However, now I am unable to access locations under the 'internal' folder.

Is there a recommended way to access the data inside internal?

Thanks!

**Comment by Plaristote** [comment]
Alright then ! 0.1.4 should fix that. Use the `prefix` option when creating the site object:

```
  Sharepoint::Site.new 'mytenant.sharepoint.com', 'folder', prefix: "internal"
```

**Comment by CJKinni** [comment]
Thanks!
