### ISSUE TITLE
curb dependencies

### ISSUE THREAD

**Issue by tchukuchuk** [Plaristote/sharepoint-ruby#46]
Hi @Plaristote ,

Thanks for your gem !

Do you know if it's possible to upgrade your curb dependencies ?

I have some issue with libcurl on Debian Buster, and it's fixed with 0.9.11 release.

Regards.

**Comment by Plaristote** [comment]
It's done in the 0.1.5 version.
I'm also about to push 0.2 as well, but this one will require Ruby 3.
