### ISSUE TITLE
Version 0.2.1 has git changes inside the code

### ISSUE THREAD

**Issue by PanchoMrlda** [Plaristote/sharepoint-ruby#52]
After we pull the gem at 0.2.1 version, raising the rails server will fail because of syntax errors due to the file sharepoint-lists.rb
![sharepoint-ruby Error](https://user-images.githubusercontent.com/22328157/165050520-ca33eefc-4473-4db8-bc6d-db9e5f589310.PNG)

**Comment by Plaristote** [comment]
Oh lord... something went wrong while pushing the package, I had a merge on-going ! I'm so sorry ! I just published 0.2.2 to take care of this issue.
