### ISSUE TITLE
Sharepoint basic authentication deprecation

### ISSUE THREAD

**Issue by aerdnac1** [Plaristote/sharepoint-ruby#54]
Hi, sorry, I need some information about the microsoft annuncement of deprecation for basic auth :

https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-september/ba-p/3609437

I would like to ask if the gem will be still able to connect to sharepoint (we use STS method)
thanks

**Comment by Plaristote** [comment]
We use NTLM rather than Basic Authentication, so it seems like we won't be affected by that change ! Hurray !
