### ISSUE TITLE
Support list queries

### ISSUE THREAD

**Issue by danmichaelson** [Plaristote/sharepoint-ruby#8]
For example to get calendar events from date to date. See docs at https://msdn.microsoft.com/en-us/library/office/fp142385.aspx . The $filter feature under "Select items to return" would be especially useful.

Or is this already supported and I'm missing something?

Thanks!

**Comment by Plaristote** [comment]
Is this issue also solved by ebd7eeeff3553e6406168eae51b90638bb255201 ?
The `item_batch` method can send a `$filter` parameter, which should do the trick.
